export interface CLRColumns {
  UserId: number;
  CLRColumnId: number;
  Client: boolean;
  RevenueID: boolean;
  Country: boolean;
  iMeet_Workspace_Title: boolean;
  Priority : boolean;
  Implementation_Type: boolean;
  Pipeline_status: boolean;
  Pipeline_comments: boolean;
  TXResourcing: boolean;
  Service_location: boolean;
  Service_configuration: boolean;
  OBT_Reseller___Direct: boolean;
  OBTAdoptionRate: boolean;
  ExpectedDecisionDate_c: boolean;
  Assignment_date_c: boolean;
  ResourseRequestedDate_c: boolean;
  UpdateOn_c: boolean;
  OppVolume: boolean;
  RevenueVolumeUSD: boolean;
  Region: boolean;
  OwnerShip: boolean;
  ProjectStart_ForCycleTime_c: boolean;
  GoLiveDate_c: boolean;
  PerCompleted: boolean;
  CycleTime: boolean;
  CycleTimeCategories: boolean;
  CycleTimeDelayCode: boolean;
  EltClientDelayDescription: boolean;
  ProjectStatus: boolean;
  Milestone__Reason_Code: boolean;
  CountryStatus: boolean;
  ProjectLevel: boolean;
  CompletedDate_c: boolean;
  GlobalProjectManager: boolean;
  RegionalProjectManager: boolean;
  AssigneeFullName: boolean;
  GlobalCISDQSLead: boolean;
  APAC_DQS: boolean;
  DQS_Import: boolean;
  DQS_Support: boolean;
  LATAM_DQS: boolean;
  NORAM_DQS: boolean;
  DQS_Operations: boolean;
  GlobalCISOBTLead: boolean;
  RegionalCISOBTLead: boolean
  LocalDigitalOBTLead: boolean
  GlobalCISPortraitLead: boolean
  RegionalCISPortraitLead: boolean
  GlobalCISHRFeedSpecialist: boolean
  GDS: boolean
  ActivityType: boolean
  ComplexityScore: boolean
  MilestoneTitle: boolean
  Group_Name: boolean
  Milestone__Project_Notes: boolean
  Milestone__Closed_Loop_Owner: boolean
  Workspace__ELT_Overall_Status: boolean
  Workspace__ELT_Overall_Comments: boolean
  NpsScore: boolean
  Customer_Row_ID: boolean
  Opportunity_ID: boolean
  AccountOwner: boolean
  Opportunity_Type: boolean
  Revenue_Status: boolean
  Revenue_Opportunity_Type: boolean
  Opportunity_Owner: boolean
  Opportunity_Category: boolean
  Revenue_Total_Transactions: boolean
  Line_Win_Probability: boolean
  Implementation_Fee__PSD_: boolean
  Next_Step: boolean
  AwardedDate_c: boolean
  DataDescription: boolean
  Date_added_to_the_CLR_c: boolean
  CreatedDate_c: boolean
  Project_Effort: boolean
  Sales_Stage_Name: boolean
  AccountCategory: boolean
  SOWStatus: boolean
  ImplementationReady: boolean
  RecordHistory_C: boolean
  DataSourceType: boolean
  DataQuality: boolean
  CreatedOn: string
}